/*
------------------------------------------------
Generated by Cradle 0.0.0.0
https://github.com/daterre/Cradle

Original file: StoryExampleWalking.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @StoryExampleWalking: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("isenglish", () => this.@isenglish, val => this.@isenglish = val);
		}

		public StoryVar @isenglish;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly StoryMacros macros1;
	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros2;

	@StoryExampleWalking()
	{
		this.StartPassage = "Untitled Passage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new StoryMacros() { Story = this };
		macros2 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Untitled Passage

	void passage1_Init()
	{
		this.Passages[@"Untitled Passage"] = new StoryPassage(@"Untitled Passage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		if(Vars.isenglish) {
			yield return lineBreak();
			yield return lineBreak();
			yield return link("How long do we need to walk?", "almostthere", null);
			yield return lineBreak();
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return lineBreak();
			yield return link("Müssen wir noch lange gehen?", "almostthere", null);
			yield return lineBreak();
			yield return lineBreak();
		}
		yield break;
	}


	// .............
	// #2: almostthere

	void passage2_Init()
	{
		this.Passages[@"almostthere"] = new StoryPassage(@"almostthere", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		if(Vars.isenglish) {
			yield return lineBreak();
			yield return lineBreak();
			yield return text("We are almost there.");
			yield return lineBreak();
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return lineBreak();
			yield return text("Wir sind bald da.");
			yield return lineBreak();
			yield return lineBreak();
		}
		yield break;
	}


}